/**
 * *********************************
 * Name: Donghu Zhang 
 * Student Number: 064361108 
 * Date:  Dec 6, 2012 
 * Assignment#: Assignment 3
 * General description of what your code does: 
 *  Create an GUI application with a virtual keyboard. When user pressed the key, 
 *  it would change the color on the virtual keyboard, reset the color when release the key
 * General description of the variables used in your code: 
 *  details variables please see the code
 * Expected good results: 
 *  Virtual keyboard would change background color when pressed, and would 
 *  reset the color when released.
 * Anticipated bad results: 
 *  None
**********************************
* */
package assignment3;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.Map;
import java.util.HashMap;

/**
 *
 * @author Donghu Zhang
 */
public class TypingTuor extends javax.swing.JFrame implements KeyListener,
        ActionListener {
  /*Map method to create a map to hold all button objects*/

  Map<Integer, javax.swing.JButton> keyButtonMap = new HashMap<Integer, javax.swing.JButton>();

  /**
   * Creates new form TypingTuor
   */
  public TypingTuor() {
    initComponents();//build GUI

    addKeyListener(this);//add listener to Frame

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  private void initComponents() {
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();
    jButtonTube = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_BACK_QUOTE, jButtonTube);
    jButtonOne = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_1, jButtonOne);
    jButtonThree = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_3, jButtonThree);
    jButtonTwo = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_2, jButtonTwo);
    jButtonFour = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_4, jButtonFour);
    jButtonFive = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_5, jButtonFive);
    jButtonSeven = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_7, jButtonSeven);
    jButtonSix = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_6, jButtonSix);
    jButtonZero = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_0, jButtonZero);
    jButtonMinus = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_MINUS, jButtonMinus);
    jButtonNine = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_9, jButtonNine);
    jButtonEight = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_8, jButtonEight);
    jButtonBS = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_BACK_SPACE, jButtonBS);
    jButtonEqual = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_EQUALS, jButtonEqual);
    jButtonRBlac = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_CLOSE_BRACKET, jButtonRBlac);
    jButtonSlash = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_BACK_SLASH, jButtonSlash);
    jButtonR = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_R, jButtonR);
    jButtonT = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_T, jButtonT);
    jButtonE = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_E, jButtonE);
    jButtonW = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_W, jButtonW);
    jButtonU = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_U, jButtonU);
    jButtonY = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_Y, jButtonY);
    jButtonQ = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_Q, jButtonQ);
    jButtonP = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_P, jButtonP);
    jButtonLBrac = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_OPEN_BRACKET, jButtonLBrac);
    jButtonO = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_O, jButtonO);
    jButtonI = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_I, jButtonI);
    jButtonTab = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_TAB, jButtonTab);
    jButtonF = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_F, jButtonF);
    jButtonEnter = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_ENTER, jButtonEnter);
    jButtonH = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_H, jButtonH);
    jButtonS = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_S, jButtonS);
    jButtonJ = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_J, jButtonJ);
    jButtonG = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_G, jButtonG);
    jButtonD = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_D, jButtonD);
    jButtonSC = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_SEMICOLON, jButtonSC);
    jButtonA = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_A, jButtonA);
    jButtonL = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_L, jButtonL);
    jButtonUComma = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_QUOTE, jButtonUComma);
    jButtonK = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_K, jButtonK);
    jButtonCaps = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_CAPS_LOCK, jButtonCaps);
    jButtonC = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_C, jButtonC);
    jButtonB = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_B, jButtonB);
    jButtonM = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_M, jButtonM);
    jButtonPeriod = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_PERIOD, jButtonPeriod);
    jButtonUp = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_UP, jButtonUp);
    jButtonSlash2 = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_SLASH, jButtonSlash2);
    jButtonZ = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_Z, jButtonZ);
    jButtonComma = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_COMMA, jButtonComma);
    jButtonShift = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_SHIFT, jButtonShift);
    jButtonV = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_V, jButtonV);
    jButtonN = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_N, jButtonN);
    jButtonX = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_X, jButtonX);
    jButtonLeft = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_LEFT, jButtonLeft);
    jButtonRight = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_RIGHT, jButtonRight);
    jButtonDown = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_DOWN, jButtonDown);
    jButtonSpace = new javax.swing.JButton();
    keyButtonMap.put(KeyEvent.VK_SPACE, jButtonSpace);

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);//CLOSE THE APPLICATION
    //USE THE <HTML> TO LINE BREAK IN AN JLabel
    jLabel2.setText("<html>Type some text using your keyboard. The keys you press will be highlighting and the text will be displayed. <br/>Note: Clicking the buttons with your mouse will not perform any action</html>");

    jTextArea1.setColumns(20);
    jTextArea1.setLineWrap(true);
    jTextArea1.setRows(5);
    jTextArea1.setWrapStyleWord(true);
    jTextArea1.addKeyListener(this);// add listener to JTextArea

    jScrollPane1.setViewportView(jTextArea1);
    //assigned value to JButton
    jButtonTube.setText("~");

    jButtonOne.setText("1");

    jButtonThree.setText("3");

    jButtonTwo.setText("2");

    jButtonFour.setText("4");

    jButtonFive.setText("5");

    jButtonSeven.setText("7");

    jButtonSix.setText("6");

    jButtonZero.setText("0");

    jButtonMinus.setText("-");

    jButtonNine.setText("9");

    jButtonEight.setText("8");

    jButtonBS.setText("Backspace");

    jButtonEqual.setText("=");

    jButtonRBlac.setText("]");

    jButtonSlash.setText("\\");

    jButtonR.setText("R");

    jButtonT.setText("T");

    jButtonE.setText("E");

    jButtonW.setText("W");

    jButtonU.setText("U");

    jButtonY.setText("Y");

    jButtonQ.setText("Q");

    jButtonP.setText("P");

    jButtonLBrac.setText("[");

    jButtonO.setText("O");

    jButtonI.setText("I");

    jButtonTab.setText("Tab");

    jButtonF.setText("F");

    jButtonEnter.setText("Enter");

    jButtonH.setText("H");

    jButtonS.setText("S");

    jButtonJ.setText("J");

    jButtonG.setText("G");

    jButtonD.setText("D");

    jButtonSC.setText(";");

    jButtonA.setText("A");

    jButtonL.setText("L");

    jButtonUComma.setText("'");

    jButtonK.setText("K");

    jButtonCaps.setText("Caps");

    jButtonC.setText("C");

    jButtonB.setText("B");

    jButtonM.setText("M");

    jButtonPeriod.setText(".");

    jButtonUp.setText("???");

    jButtonSlash2.setText("/");

    jButtonZ.setText("Z");

    jButtonComma.setText(",");

    jButtonShift.setText("Shift");

    jButtonV.setText("V");

    jButtonN.setText("N");

    jButtonX.setText("X");

    jButtonLeft.setText("???");

    jButtonRight.setText("???");

    jButtonDown.setText("???");

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
            .add(jLabel1)
            .add(18, 18, 18)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
            .add(layout.createSequentialGroup()
            .add(jButtonTab, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonQ, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonW, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonR, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonT, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonY, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonU, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonI, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonO, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonLBrac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonRBlac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonSlash, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
            .add(jButtonTube, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonOne, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonTwo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonThree, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonFour, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonFive, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonSix, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonSeven, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonEight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonNine, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonZero, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonMinus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonEqual, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonBS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1)
            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel2)
            .add(layout.createSequentialGroup()
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
            .add(jButtonCaps, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonA, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonD, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonG, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonH, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonJ, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonK, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonSC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonUComma, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
            .add(layout.createSequentialGroup()
            .add(jButtonShift, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 117, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
            .add(jButtonZ, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonX, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
            .add(jButtonC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonV, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonM, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonComma, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonPeriod, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonSlash2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(layout.createSequentialGroup()
            .add(6, 6, 6)
            .add(jButtonSpace, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 339, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
            .add(28, 28, 28)))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jButtonUp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonEnter, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
            .add(layout.createSequentialGroup()
            .add(jButtonLeft, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonDown, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButtonRight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(16, Short.MAX_VALUE)));
    layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(layout.createSequentialGroup()
            .add(17, 17, 17)
            .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 221, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
            .add(jButtonTube, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonOne, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonTwo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonThree, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonFour, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonFive, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonSix, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonSeven, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonEight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonNine, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonZero, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonMinus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonEqual, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonBS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
            .add(jButtonQ, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonW, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonR, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonT, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonY, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonU, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonI, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonO, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonLBrac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonRBlac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonSlash, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonTab, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
            .add(jButtonA, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonD, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonG, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonH, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonJ, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonK, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonSC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonUComma, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonEnter, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonCaps, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jButtonShift, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
            .add(jButtonZ, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonX, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonV, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonM, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonComma, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonPeriod, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonSlash2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonUp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
            .add(jButtonLeft, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonDown, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonRight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jButtonSpace, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(15, Short.MAX_VALUE)));

    pack();
  }

  private void jButtonQKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonQKeyPressed
    System.out.println("here");
  }//GEN-LAST:event_jButtonQKeyPressed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(TypingTuor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(TypingTuor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(TypingTuor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(TypingTuor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        TypingTuor tuor = new TypingTuor();
        tuor.setVisible(true);
        tuor.setFocusable(true);///VERY IMPORTANT!!!
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonA;
  private javax.swing.JButton jButtonB;
  private javax.swing.JButton jButtonBS;
  private javax.swing.JButton jButtonC;
  private javax.swing.JButton jButtonCaps;
  private javax.swing.JButton jButtonComma;
  private javax.swing.JButton jButtonD;
  private javax.swing.JButton jButtonDown;
  private javax.swing.JButton jButtonE;
  private javax.swing.JButton jButtonEight;
  private javax.swing.JButton jButtonEnter;
  private javax.swing.JButton jButtonEqual;
  private javax.swing.JButton jButtonF;
  private javax.swing.JButton jButtonFive;
  private javax.swing.JButton jButtonFour;
  private javax.swing.JButton jButtonG;
  private javax.swing.JButton jButtonH;
  private javax.swing.JButton jButtonI;
  private javax.swing.JButton jButtonJ;
  private javax.swing.JButton jButtonK;
  private javax.swing.JButton jButtonL;
  private javax.swing.JButton jButtonLBrac;
  private javax.swing.JButton jButtonLeft;
  private javax.swing.JButton jButtonM;
  private javax.swing.JButton jButtonMinus;
  private javax.swing.JButton jButtonN;
  private javax.swing.JButton jButtonNine;
  private javax.swing.JButton jButtonO;
  private javax.swing.JButton jButtonOne;
  private javax.swing.JButton jButtonP;
  private javax.swing.JButton jButtonPeriod;
  private javax.swing.JButton jButtonQ;
  private javax.swing.JButton jButtonR;
  private javax.swing.JButton jButtonRBlac;
  private javax.swing.JButton jButtonRight;
  private javax.swing.JButton jButtonS;
  private javax.swing.JButton jButtonSC;
  private javax.swing.JButton jButtonSeven;
  private javax.swing.JButton jButtonShift;
  private javax.swing.JButton jButtonSix;
  private javax.swing.JButton jButtonSlash;
  private javax.swing.JButton jButtonSlash2;
  private javax.swing.JButton jButtonSpace;
  private javax.swing.JButton jButtonT;
  private javax.swing.JButton jButtonTab;
  private javax.swing.JButton jButtonThree;
  private javax.swing.JButton jButtonTube;
  private javax.swing.JButton jButtonTwo;
  private javax.swing.JButton jButtonU;
  private javax.swing.JButton jButtonUComma;
  private javax.swing.JButton jButtonUp;
  private javax.swing.JButton jButtonV;
  private javax.swing.JButton jButtonW;
  private javax.swing.JButton jButtonX;
  private javax.swing.JButton jButtonY;
  private javax.swing.JButton jButtonZ;
  private javax.swing.JButton jButtonZero;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea jTextArea1;
  // End of variables declaration//GEN-END:variables

  @Override
  public void keyTyped(KeyEvent e) {
 
  }

  @Override
  public void actionPerformed(ActionEvent e) {
   
  }

  @Override
  public void keyPressed(KeyEvent e) {
    //System.out.println("here pressed");
    //System.out.println(e.getKeyCode());
    /*set color when pressed*/
    if (keyButtonMap.containsKey(e.getKeyCode())) {
      keyButtonMap.get(e.getKeyCode()).setBackground(Color.green);
    }//end if
  }//end of keyPressed

  @Override
  public void keyReleased(KeyEvent e) {
    //System.out.println("here release");
    //System.out.println(e.getKeyCode());
    /*set color when released*/
    Color c = new Color(238,238,238);
    if (keyButtonMap.containsKey(e.getKeyCode())) {
      keyButtonMap.get(e.getKeyCode()).setBackground(c);
    }//end if
  }//end keyReleased
}//end of class TypingTuor
